# Generated by Django 5.1.3 on 2025-08-18 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_landlord',
            new_name='landlord',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_tenant',
            new_name='tenant',
        ),
    ]
